baseURL = 'https://larrymuhlstein.com'
languageCode = 'en-us'
title = 'larry muhlstein'
theme = 'hugo-cat'

# PygmentsCodeFences = true
# PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 15
disableHugoGeneratorInject = false
enableEmoji = true

[params]
ava = "/static/images/heartflower.svg"
owner ="larry muhlstein"
# talk = "Hello guys &#128075; im cool kitty..."
blogSection = ["perspective"]
# description = "larry muhlstein personal site"
favicon = "/img/favicon.ico"

[[menu.main]]
name = "vision"
url = "/"
weight = 1

[[menu.main]]
name = "etiology"
url = "/etiology/"
weight = 2

[[menu.main]]
name = "dharma"
url = "/dharma/"
weight = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"
  
