baseURL = 'https://larrymuhlstein.com'
languageCode = 'en-us'
title = 'larry muhlstein'
theme = 'hugo-cat'

PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 15
disableHugoGeneratorInject = false
enableEmoji = true

[params]
ava = "/img/larry-shadow.jpg"
owner ="larry muhlstein"
talk = "Hello guys &#128075; im cool kitty..."
blogSection = ["blog"]
description = "larry muhlstein personal site"
favicon = "/img/logo.svg"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Vision"
url = "/vision/"
weight = 2

[[menu.main]]
name = "Dharma"
url = "/dharma/"
weight = 3

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 4

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"
  
